version: "3.8"

services:
  reverse-proxy:
    build: .
    ports:
      - "42000:42000"
    environment:
      - NODE_ENV=production
      - PROXY_PORT=42000
      - SOCKS_PROXY=socks5://host.docker.internal:18086
      # IMPORTANT: Pass your secret API key to the container
      # Replace 'YOUR_SUPER_SECRET_KEY_HERE' with your actual key.
      - EXPECTED_API_KEY=YOUR_SUPER_SECRET_KEY_HERE
    networks:
      - proxy-network
    restart: unless-stopped

networks:
  proxy-network:
    driver: bridge
